#! /usr/bin/bash
args="$@"
site_mirror="https\:\/\/mirror\.ghproxy\.com\/https\:\/\/github\.com"
github_site="https\:\/\/github\.com"

download_site=$(echo $args | sed "s/$github_site/$site_mirror/")
# if expr match $args "https\:\/\/github\.com"; then
# 	download_site=$site_mirror$args
# fi
echo -e "\033[41;36m wget download from $download_site \033[0m"
/usr/bin/curl $download_site
